import Layout from "@/layout/Layout";
import PageBanner from "@/layout/PageBanner";

const About = () => {
  return (
    <Layout pageName={"About"}>
      <PageBanner pageName={"Legal Documents"} />
      <div className="neoh_fn_aboutpage">
        {/* Information Section */}
        <section id="information">
          <div className="container">
            {/* About Item #1 */}
            <div className="neoh_fn_about_item">
              {/* <div className="img_item">
                <img src="img/about/1.jpg" alt="" />
              </div> */}
              <div className="content_item">
                <div className="neoh_fn_title" data-align="left">
                  <h3 className="fn_title">TERMS AND CONDITIONS</h3>
                  <div className="line">
                    <span />
                  </div>
                </div>
                <div className="desc">
                  <p>
                  Carbon.Std is a collection of digital artworks (NFTs) running on the Ethereum network. This site is just an interface that allows participants to purchase digital collectibles. Users are entirely responsible for the security and management of their own private Ethereum wallets and for validating all transactions and contracts generated by this website before approval. Furthermore,like the contract Carbon.Std's smart run on the Ethereum network, there is no ability to undo, reverse or restore any transactions.
                  </p>
                  <p>
                  It's Website and its Connected services are provided “as is” and “as available” without warranty of any kind. By using this website, you accept responsibility exclusive for any and all transactions involving Carbon.Std digital collectibles.</p>
                </div>
                {/* <div className="buttons">
                  <a
                    href="https://opensea.io/CarbonStd"
                    target="_blank"
                    rel="noreferrer"
                    className="neoh_fn_button"
                  >
                    <span className="icon">
                      <img src="svg/opensea.svg" alt="" className="fn__svg" />
                    </span>
                    <span className="text">OpenSea</span>
                  </a>
                  <a
                    href="https://discord.com/invite/sDMzchFsmp"
                    target="_blank"
                    rel="noreferrer"
                    className="neoh_fn_button"
                  >
                    <span className="icon">
                      <img src="svg/discord.svg" alt="" className="fn__svg" />
                    </span>
                    <span className="text">Discord</span>
                  </a>
                </div> */}
              </div>
              <div className="content_item">
                <div className="neoh_fn_title" data-align="left">
                  <h3 className="fn_title">Property</h3>
                </div>
                <div className="desc">
                  <p>
                  A. You Own the NFT. Each Carbon.Std is an NFT on the Ethereum blockchain. When you buy an NFT, you own the underlying Carbon.Std, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no time can we seize, freeze or modify ownership of any Carbon.Std.
                  </p>
                  <p>
                  B. Personal use. Subject to your continued compliance with these Terms, Stock Capital grants you a worldwide royalty-free license to use, copy and display the purchased Artwork, along with any extensions you choose to create or use, exclusively for the following purposes: (i) toits use personal and non-commercial; (ii) as part of a marketplace that allows the buying and selling of your Carbon.Std/NFT, provided the marketplace cryptographically verifies the rights of each Carbon.Std owner to display the Artwork from your Carbon.Std to ensure only the actual owner can display the Artwork; or (iii) as part of a third party website or application that allow inclusion, involvement or participation of its Carbon.Std.</p>
                  <p>
                  C. Commercial Use. Subject to your continued compliance with these Terms, Stock Capital grants you an unlimited worldwide license to use, copy and display Artwork purchased for the purpose of creating derivative works based on the Artwork (“Commercial Use”). Examples of such Commercial Use would be, for example, using the Artwork to produce and sell merchandise (t-shirts, etc.) displaying copies of the Artwork. For the sake of clarity, nothing in this Section shall be deemed to preclude (i) owning or operating a marketplace that permits the use and sale of Carbon.Std generally, provided the marketplace cryptographically verifies the rights of each Carbon.Std owner to display the Artwork to your Carbon.Std to ensure only the actual owner can display the Artwork; (ii) own or operate a third party website or application that allow inclusion, involvement or participation of Carbon.Std generally, provided that the third party website or application cryptographically verifies the rights of each owner of Carbon.Std To display Artwork from your Carbon.Std to ensure only the actual owner can display the art and since that Art is no longer visiblewhen the owner from the Purchased Carbon.Std leave the website/application; or (iii) obtain revenue from any of the foregoing items. as long as the third-party website or application cryptographically verifies the rights of each Carbon.Std owner to display Artwork for your Carbon.Std to ensure only the actual owner can display the art and since that the Artwork is no longer visible once the owner of the Purchased Carbon.Std leaves the website/application; or (iii) obtain revenue from any of the foregoing items. as long as the third-party website or application cryptographically verifies the rights of each Carbon.Std owner to display Artwork for your Carbon.Std to ensure only the actual owner can display the art and since that the Artwork is no longer visible once the owner of the Purchased Carbon.Std leaves the website/application; or (iii) obtain revenue from any of the foregoing items.</p>
                  <p>D. Carbon.Std/IP. Other than rights in the Artwork, nothing herein gives you any rights in any other trademarks or other intellectual property rights belonging to Stock Capital, including, without limitation, Carbon.Std, and the associated logos. All such rights are expressly reserved on behalf of Stock Capital.</p>
                  <p>E. Comments. You may choose to submit comments, bug reports, ideas or other feedback about the Site, including, without limitation, how to improve the Site (collectively, “Feedback”). By submitting any Feedback, you agree that we are free to use such Feedback in any manner that we choose without further compensation to you and you grant us a perpetual, irrevocable, non-exclusive, worldwide license to incorporate and use the Feedback for any purpose.</p>
                </div>
              </div>
            </div>
            {/* !About Item #1 */}
            {/* Guarantee List */}
            {/* <div className="neoh_fn_gualist">
              <ul>
                <li>
                  <div className="item">
                    <span className="line" />
                    <img
                      src="svg/search-engine.svg"
                      alt=""
                      className="fn__svg"
                    />
                    <h3 className="fn_title">Transparency</h3>
                    <p className="fn_desc fn_animated_text">
                      Morbi non dignissim erat, a blandit felis. Suspendisse nec
                      lorem vel orci varius congue ut vitae est.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="item">
                    <span className="line" />
                    <img src="svg/management.svg" alt="" className="fn__svg" />
                    <h3 className="fn_title">Experienced Team</h3>
                    <p className="fn_desc fn_animated_text">
                      Morbi non dignissim erat, a blandit felis. Suspendisse nec
                      lorem vel orci varius congue ut vitae est.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="item">
                    <span className="line" />
                    <img src="svg/padlock.svg" alt="" className="fn__svg" />
                    <h3 className="fn_title">Security Guarantee</h3>
                    <p className="fn_desc fn_animated_text">
                      Morbi non dignissim erat, a blandit felis. Suspendisse nec
                      lorem vel orci varius congue ut vitae est.
                    </p>
                  </div>
                </li>
              </ul>
            </div> */}
            {/* !Guarantee List */}
            {/* About Item #2 */}
            {/* <div className="neoh_fn_about_item reverse">
              <div className="img_item">
                <img src="img/about/2.jpg" alt="" />
              </div>
              <div className="content_item">
                <div className="neoh_fn_title" data-align="left">
                  <h3 className="fn_title">Thousands of Users</h3>
                  <div className="line">
                    <span />
                  </div>
                </div>
                <div className="desc">
                  <p>
                    Simply holding a Neoh will give you access to seasonal
                    airdrops, merchandise, physical and digital artworks,
                    collectibles and more.
                  </p>
                  <p>
                    We understand the importance of the cross-over between these
                    worlds and we truly believe to bridge these two together.
                    Our goals will always be for the community - creating,
                    building and innovating together with the commmunity.
                  </p>
                </div>
                <div className="buttons">
                  <a href="#" className="neoh_fn_button only_text">
                    <span className="text">Join Community</span>
                  </a>
                </div>
              </div>
            </div> */}
            {/* !About Item #2 */}
          {/* </div>
        </section> */}
        {/* !Information Section */}
        {/* Video Section */}
        {/* <section id="video"> */}
          {/* Dividers */}
          {/* <img
            src="svg/divider.svg"
            alt=""
            className="fn__svg fn__divider top_divider"
          />
          <img
            src="svg/divider.svg"
            alt=""
            className="fn__svg fn__divider bottom_divider"
          /> */}
          {/* !Dividers */}
          {/* Video Shortcode */}
          {/* <div className="neoh_fn_video">
            <div className="bg_overlay">
              <div className="bg_image" data-bg-img="img/hero/bg.jpg" />
              <div className="bg_color" />
            </div>
            <div className="v_content">
              <a
                className="popup-youtube"
                href="//www.youtube.com/embed/7e90gBu4pas?autoplay=1"
              >
                <img src="svg/play.svg" alt="" className="fn__svg" />
              </a>
            </div>
          </div> */}
          {/* !Video Shortcode */}
        {/* </section> */}
        {/* !Video Section */}
        {/* Team Section */}
        {/* <section id="team">
          <div className="container"> */}
            {/* Main Title */}
            {/* <div className="neoh_fn_title">
              <h3 className="fn_title">Our Team Members</h3>
              <div className="line">
                <span />
              </div>
            </div> */}
            {/* !Main Title */}
            {/* <div className="mw_650 fn_description">
              <p className="fn_desc fn_animated_text">
                The idea was born in London and rapidly became a borderless
                vision - A team of Neoh with a background in computer graphics,
                crypto, technology, and art.
              </p>
            </div> */}
            {/* Team List Shortcode */}
            {/* <div className="neoh_fn_team">
              <ul className="team_list">
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/1.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Tom Mccarthy</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/2.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Owen Bradley</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/3.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Daniel Bradley</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/4.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Skylar Jarvis</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/5.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Avery Briggs</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
                <li className="team_item">
                  <div className="t_item">
                    <div className="person_info">
                      <div className="img_holder">
                        <img src="img/author/6.jpg" alt="" />
                      </div>
                      <div className="title_holder">
                        <h3 className="fn_title">Bernard Green</h3>
                        <p className="fn_desc">2D Artist</p>
                      </div>
                    </div>
                    <div className="person_social">
                      <ul>
                        <li>
                          <a href="#">
                            <i className="fn-icon-twitter" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-facebook" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-instagram" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-pinterest" />
                          </a>
                        </li>
                        <li>
                          <a href="#">
                            <i className="fn-icon-behance" />
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li>
              </ul>
            </div> */}
            {/* !Team List Shortcode */}
          </div>
        </section>
        {/* !Team Section */}
      </div>
    </Layout>
  );
};
export default About;
