import Layout from "@/layout/Layout";
import PageBanner from "@/layout/PageBanner";

const About = () => {
  return (
    <Layout pageName={"Buy Now"}>
      <PageBanner pageName={"Buy Now"} />
      <div className="neoh_fn_aboutpage">
        <section id="information">
          <div className="container">
            <div className="neoh_fn_about_item">
              <div className="content_item">
                <div className="neoh_fn_title" data-align="left">
                  <h3 className="fn_title">BUY NOW</h3>
                  <div className="line">
                    <span />
                  </div>
                </div>
                <div className="desc">
                  <p>
                  Carbon.Std is a collection of digital artworks (NFTs) running on the Ethereum network. This site is just an interface that allows participants to purchase digital collectibles. Users are entirely responsible for the security and management of their own private Ethereum wallets and for validating all transactions and contracts generated by this website before approval. Furthermore,like the contract Carbon.Std's smart run on the Ethereum network, there is no ability to undo, reverse or restore any transactions.
                  </p>
                  <p>
                  It's Website and its Connected services are provided “as is” and “as available” without warranty of any kind. By using this website, you accept responsibility exclusive for any and all transactions involving Carbon.Std digital collectibles.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
};
export default About;
